### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fizwit** [aertslab/pySCENIC#499]
numpy.object is deprecated >numpy-1.24.0 

Fix: replace numpy.object with object

**Steps to reproduce the behavior**
```
build with numpy>1.24
```
- pySCENIC version: [e.g. 0.12.1, use `pyscenic -h` at the command line]
```
pyscenic --help 
 /app/software/pySCENIC/0.12.1-foss-2022b/lib/python3.10/site-packages/pyscenic/transform.py:42: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  ("Enrichment", COLUMN_NAME_ANNOTATION): np.object,
Traceback (most recent call last):
  File "/app/software/pySCENIC/0.12.1-foss-2022b/bin/pyscenic", line 5, in <module>
    from pyscenic.cli.pyscenic import main
  File "/app/software/pySCENIC/0.12.1-foss-2022b/lib/python3.10/site-packages/pyscenic/cli/pyscenic.py", line 26, in <module>
    from pyscenic.prune import _prepare_client, find_features, prune2df
  File "/app/software/pySCENIC/0.12.1-foss-2022b/lib/python3.10/site-packages/pyscenic/prune.py", line 27, in <module>
    from .transform import (
  File "/app/software/pySCENIC/0.12.1-foss-2022b/lib/python3.10/site-packages/pyscenic/transform.py", line 42, in <module>
    ("Enrichment", COLUMN_NAME_ANNOTATION): np.object,
  File "/app/software/SciPy-bundle/2023.02-gfbf-2022b/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'object_'?
```

**Comment by fizwit** [comment]
# Fix numpy.object issue

```
diff -ruN pyscenic-0.12.1.orig/src/pyscenic/transform.py pyscenic-0.12.1/src/pyscenic/transform.py
--- pyscenic-0.12.1.orig/src/pyscenic/transform.py      2022-11-21 02:38:05.000000000 -0800
+++ pyscenic-0.12.1/src/pyscenic/transform.py   2023-08-14 16:10:51.606682000 -0700
@@ -39,9 +39,9 @@
         ("Enrichment", COLUMN_NAME_NES): np.float64,
         ("Enrichment", COLUMN_NAME_MOTIF_SIMILARITY_QVALUE): np.float64,
         ("Enrichment", COLUMN_NAME_ORTHOLOGOUS_IDENTITY): np.float64,
-        ("Enrichment", COLUMN_NAME_ANNOTATION): np.object,
-        ("Enrichment", COLUMN_NAME_CONTEXT): np.object,
-        ("Enrichment", COLUMN_NAME_TARGET_GENES): np.object,
+        ("Enrichment", COLUMN_NAME_ANNOTATION): object,
+        ("Enrichment", COLUMN_NAME_CONTEXT): object,
+        ("Enrichment", COLUMN_NAME_TARGET_GENES): object,
         ("Enrichment", COLUMN_NAME_RANK_AT_MAX): np.int64,
     },
     index=pd.MultiIndex.from_arrays(
```

**Comment by fizwit** [comment]
I see this is fixed in "master" but not in 0.12.1.  Closing issue
