### ISSUE TITLE
import module error

### ISSUE THREAD

**Issue by wangjiawen2013** [aertslab/pySCENIC#19]
Dear, 
I met an error "TypeError: attr() got an unexpected keyword argument 'converter'" when I type the following code  as the tutorials do:

from pyscenic.rnkdb import FeatherRankingDatabase as RankingDatabase
from pyscenic.utils import modules_from_adjacencies, load_motifs
from pyscenic.prune import prune, prune2df, df2regulons
from pyscenic.aucell import aucell

here is the whole output:
>>> from pyscenic.rnkdb import FeatherRankingDatabase as RankingDatabase
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wangjw/data/bin/python3.6/lib/python3.6/site-packages/pyscenic/rnkdb.py", line 10, in <module>
    from .genesig import GeneSignature
  File "/home/wangjw/data/bin/python3.6/lib/python3.6/site-packages/pyscenic/genesig.py", line 31, in <module>
    class GeneSignature(yaml.YAMLObject):
  File "/home/wangjw/data/bin/python3.6/lib/python3.6/site-packages/pyscenic/genesig.py", line 120, in GeneSignature
    gene2weight = attr.ib(converter=convert)  # Mapping[str, float]
TypeError: attr() got an unexpected keyword argument 'converter'
 What's the cause of this error?

**Comment by wangjiawen2013** [comment]
attr(default=NOTHING, validator=None, repr=True, cmp=True, hash=None, init=True, convert=None, metadata={})

Is it caused by the keyword parameter 'convert' ?

**Comment by wangjiawen2013** [comment]
Thanks!
The problem has been solved when upgrade attrs to 18.2.0
However,  when I ran adjacencies = grnboost2(ex_matrix, tf_names=tf_names, verbose=True)
the following error occured:
BufferError: Existing exports of data: object cannot be re-sized
According to google, maybe the problem is involved in tornado and mutli-threads ( I am not sure about that), Could you give me some advices?
